name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install server dependencies
        working-directory: server
        run: npm ci

      - name: Lint (ESLint)
        working-directory: server
        run: |
          npx eslint . || true

      - name: Basic server syntax check
        working-directory: server
        env:
          JWT_SECRET: test
          PORT: 5000
        run: |
          node -c server.js 2>/dev/null || echo "Skipping as node -c isn't supported"
          node -e "require('./server.js'); process.exit(0);" || true
